// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using missinglink.Contexts;

namespace missinglink.Migrations
{
    [DbContext(typeof(BusContext))]
    [Migration("20210810200032_UpdatingBus")]
    partial class UpdatingBus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("missinglink.Models.Bus", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("text");

                    b.Property<int>("Delay")
                        .HasColumnType("integer");

                    b.Property<string>("RouteDescription")
                        .HasColumnType("text");

                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<string>("RouteLongName")
                        .HasColumnType("text");

                    b.Property<string>("RouteShortName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StopId")
                        .HasColumnType("text");

                    b.Property<string>("TripId")
                        .HasColumnType("text");

                    b.HasKey("VehicleId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("missinglink.Models.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("StopCode")
                        .HasColumnType("text");

                    b.Property<string>("StopDescription")
                        .HasColumnType("text");

                    b.Property<string>("StopId")
                        .HasColumnType("text");

                    b.Property<decimal>("StopLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StopLon")
                        .HasColumnType("numeric");

                    b.Property<string>("StopName")
                        .HasColumnType("text");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BusStops");
                });
#pragma warning restore 612, 618
        }
    }
}
